spring:
  redis:
    database: 0
    host: 192.168.0.107
    password: #默认为空
    port: 6380
    #      max-idle: 8 #最大空闲连接
    #      min-idle: 0 #最小空闲连接
    #      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
  main:
    allow-bean-definition-overriding: true
kafka:
  #
  # bootstrap_servers: localhost:9092
  bootstrap-servers: 192.168.0.61:9092
  group-id: watchval
  enable-auto-commit: true
  auto-commit-interval-ms: 1000
  auto-offset_reset: earliest
  session-timeout-ms: 30000
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  topic: watchval
