spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.0.107
    password: #默认为空
    port: 6380
    #      max-idle: 8 #最大空闲连接
    #      min-idle: 0 #最小空闲连接
    #      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.107:3307/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
kafka:
  #
  # bootstrap_servers: localhost:9092
  bootstrap-servers: 192.168.0.61:9092
  group-id: dfbpval
  enable-auto-commit: true
  auto-commit-interval-ms: 1000
  auto-offset_reset: earliest
  session-timeout-ms: 30000
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  topic: dfbpval
  api-url: http://192.168.3.163:11020/api/rpt/val/position
mybatis:
  type-aliases-package: com.win.dfbp.entity
  mapper-locations: classpath*:com/**/dao/**/*.xml

